# Generated by Django 4.1.7 on 2023-07-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='name')),
                ('product_desc', models.TextField(verbose_name='description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost')),
                ('product_created', models.DateTimeField(verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product/', verbose_name='image')),
                ('product_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_product', models.ManyToManyField(related_name='alternative_product', to='pages.product', verbose_name='Alternative Product')),
                ('main_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='pages.product', verbose_name='Main Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_accessory', models.ManyToManyField(related_name='alternative_accessory', to='pages.product', verbose_name='Alternative accessory')),
                ('main_accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_accessory', to='pages.product', verbose_name='Main accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100, verbose_name='name')),
                ('Category_desc', models.TextField(verbose_name='description')),
                ('Category_image', models.ImageField(upload_to='categories/')),
                ('Category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='general product')),
            ],
        ),
    ]
