# Generated by Django 4.2.3 on 2023-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
