# Generated by Django 4.2.3 on 2023-07-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_created',
        ),
    ]
