# Generated by Django 4.1.7 on 2023-07-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_product_size_product_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='general product'),
        ),
    ]
