# Generated by Django 4.1.7 on 2023-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='product/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
