# Generated by Django 4.2.3 on 2023-07-25 10:43

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='pages.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='pages.category'),
        ),
    ]
