# Generated by Django 4.1.7 on 2023-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_product_image_product_product_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_model',
            new_name='product_brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
