# Generated by Django 4.2.3 on 2023-07-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_product_product_brand_name_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_parent',
        ),
    ]
