# Generated by Django 4.1.7 on 2023-07-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='email_name',
            new_name='email',
        ),
    ]
