# Generated by Django 4.2.3 on 2023-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile_phone_number_profile_state_profile_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
