# Generated by Django 4.1.7 on 2023-07-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
    ]
