# Generated by Django 4.2.3 on 2023-07-05 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=100)),
                ('order_desc', models.TextField(blank=True, null=True)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_price', models.FloatField(default=0.0)),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
